# This file shows the structure of secrets needed for Streamlit Cloud deployment
# In Streamlit Cloud, go to App Settings → Secrets and add these values:

# GOOGLE_API_KEY = "your_google_api_key_here"
# GOOGLE_MODEL = "gemini-1.5-flash"
# PRIORITIZER_CONFIDENCE_THRESHOLD = "0.7"
# ENABLE_ENHANCED_CONTEXT = "true"
# ENABLE_VISUAL_FEEDBACK = "true"
# DEBUG_MODE = "false"